/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define if memory allocation logging and debugging is desired */
/* #undef DEBUG_ALLOCS */

/* Define if libAfterBase is available */
/* #undef HAVE_AFTERBASE */

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_DIRENT_H */

/* Define if libFreeType is available */
/* #define HAVE_FREETYPE 1 */

/* Define if libFreeType is available */
/* #define HAVE_FREETYPE_FREETYPE 1 */

/* Define to 1 if you have the <ft2build.h> header file. */
/* #undef HAVE_FT2BUILD_H */

/* Define if libgif is available */
/* #undef HAVE_GIF */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if libjpeg is available */
/* #define HAVE_JPEG 1 */

/* Define if support for XPM images should be through libXpm */
/* #undef HAVE_LIBXPM */

/* Define if support for XPM images should be through libXpm library in Xlib
   */
/* #undef HAVE_LIBXPM_X11 */

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if CPU supports MMX instructions */
/* #define HAVE_MMX 1 */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define if libpng is available */
/* #define HAVE_PNG 1 */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/dirent.h> header file. */
/* #undef HAVE_SYS_DIRENT_H */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
/* #define HAVE_SYS_TIME_H 1  */

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define if libtiff is available */
/* #define HAVE_TIFF 1 */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if support for XPM images is desired */
#define HAVE_XPM 1

/* Define if locale support in X is needed */
/* #undef I18N */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "as-bugs@afterstep.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libAfterImage"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libAfterImage 0.99"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libAfterImage.tar"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.99"

/* Support for shaped windows */
/* #define SHAPE 1 */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
/*#define TIME_WITH_SYS_TIME 1 */ 

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define if support for shared memory XImages is available */
/* #undef XSHMIMAGE */

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
#define inline 
