/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/cvsroot/afterstep-stable/src/Script/lex.yy.c,v 1.1 2000/10/20 03:27:56 sashav Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif /* __STDC__ */
#endif /* ! __cplusplus */

#ifdef __TURBOC__
#pragma warn -rch
#pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *      if ( condition_holds )
 *              yyless( 5 );
 *      else
 *              do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
  {
    FILE *yy_input_file;

    char *yy_ch_buf;		/* input buffer */
    char *yy_buf_pos;		/* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
  };

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO ((FILE * input_file));

void yy_switch_to_buffer YY_PROTO ((YY_BUFFER_STATE new_buffer));
void yy_load_buffer_state YY_PROTO ((void));
YY_BUFFER_STATE yy_create_buffer YY_PROTO ((FILE * file, int size));
void yy_delete_buffer YY_PROTO ((YY_BUFFER_STATE b));
void yy_init_buffer YY_PROTO ((YY_BUFFER_STATE b, FILE * file));
void yy_flush_buffer YY_PROTO ((YY_BUFFER_STATE b));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO ((char *base, yy_size_t size));
YY_BUFFER_STATE yy_scan_string YY_PROTO ((yyconst char *yy_str));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO ((yyconst char *bytes, int len));

static void *yy_flex_alloc YY_PROTO ((yy_size_t));
static void *yy_flex_realloc YY_PROTO ((void *, yy_size_t));
static void yy_flex_free YY_PROTO ((void *));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO ((void));
static yy_state_type yy_try_NUL_trans YY_PROTO ((yy_state_type current_state));
static int yy_get_next_buffer YY_PROTO ((void));
static void yy_fatal_error YY_PROTO ((yyconst char msg[]));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[837] =
{0,
 1, 1, 93, 90, 1, 91, 2, 90, 85, 86,
 87, 87, 84, 74, 80, 77, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 92, 92,
 1, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 1, 2, 2, 88,
 88, 87, 75, 78, 79, 76, 90, 90, 90, 70,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 69, 0, 89, 1, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 90, 90, 90, 90, 28, 90, 90, 90, 90, 90,

 71, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 41,
 90, 43, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 0, 0, 0, 0, 28,
 0, 0, 0, 0, 0, 71, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 90, 90, 90, 90, 90, 13,
 90, 90, 63, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 58, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,

 73, 90, 90, 90, 90, 90, 90, 90, 90, 42,
 90, 90, 90, 90, 90, 90, 72, 0, 0, 0,
 0, 0, 13, 0, 0, 63, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 58, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 90, 90, 90, 90, 90, 90, 14, 90,
 90, 90, 23, 61, 12, 90, 90, 90, 90, 90,
 60, 90, 90, 90, 90, 16, 90, 90, 15, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,

 0, 0, 0, 0, 0, 0, 14, 0, 0, 0,
 23, 61, 12, 0, 0, 0, 0, 0, 60, 0,
 0, 0, 0, 16, 0, 0, 15, 0, 0, 0,
 0, 0, 0, 90, 83, 0, 90, 90, 24, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 21, 18, 90, 81, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 25, 90,
 90, 90, 90, 90, 90, 90, 0, 83, 0, 0,
 24, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 21, 18, 0, 81, 0,

 0, 0, 90, 0, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 10, 90, 90, 90, 90, 90, 90, 49, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 44, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 10, 0, 0,
 90, 0, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 34, 35, 40, 90, 90, 39,

 90, 90, 90, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 90, 0, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 20, 19, 90,
 17, 11, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 36, 90, 90, 90, 90,
 90, 90, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 20, 19, 0, 17,
 11, 0, 0, 0, 0, 0, 0, 0, 0, 0,

 0, 0, 7, 0, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 6, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
 90, 90, 90, 90, 90, 90, 90, 90, 90, 7,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 6, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 90, 55, 90,
 54, 90, 90, 90, 52, 90, 90, 68, 29, 90,
 90, 59, 90, 90, 30, 67, 90, 90, 90, 4,
 90, 90, 90, 37, 90, 90, 90, 90, 90, 90,

 38, 0, 55, 0, 54, 0, 0, 0, 52, 0,
 0, 68, 29, 0, 0, 59, 0, 0, 30, 67,
 0, 0, 0, 4, 0, 0, 0, 90, 90, 90,
 90, 90, 53, 31, 90, 90, 90, 8, 22, 64,
 90, 3, 65, 90, 90, 90, 45, 90, 90, 90,
 0, 0, 0, 0, 0, 53, 31, 0, 0, 0,
 8, 22, 64, 0, 3, 65, 0, 90, 90, 90,
 90, 90, 9, 90, 66, 90, 26, 90, 90, 90,
 90, 90, 0, 0, 0, 0, 0, 9, 0, 66,
 0, 0, 90, 90, 90, 90, 90, 62, 90, 90,

 90, 27, 90, 48, 0, 0, 0, 0, 0, 62,
 0, 0, 90, 90, 32, 33, 51, 5, 90, 46,
 90, 0, 0, 32, 33, 51, 5, 82, 57, 56,
 90, 47, 57, 56, 50, 0
};

static yyconst int yy_ec[256] =
{0,
 1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 2, 1, 1, 4, 5, 1, 1, 1, 6,
 7, 1, 8, 1, 8, 1, 1, 9, 9, 9,
 9, 9, 9, 9, 9, 9, 9, 10, 1, 11,
 12, 13, 1, 1, 14, 15, 16, 17, 18, 19,
 20, 21, 22, 1, 1, 23, 24, 25, 26, 27,
 28, 29, 30, 31, 1, 32, 33, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 34, 35, 36, 37,

 38, 39, 40, 41, 42, 1, 43, 44, 45, 46,
 47, 48, 1, 49, 50, 51, 52, 53, 54, 55,
 56, 57, 58, 1, 59, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1
};

static yyconst int yy_meta[60] =
{0,
 1, 2, 3, 1, 1, 2, 2, 1, 1, 1,
 2, 2, 2, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 4, 2
};

static yyconst short int yy_base[842] =
{0,
 0, 58, 909, 0, 906, 910, 59, 902, 910, 910,
 897, 896, 0, 50, 892, 891, 865, 867, 22, 856,
 861, 45, 864, 845, 45, 858, 30, 37, 64, 910,
 122, 60, 59, 54, 58, 59, 57, 69, 77, 78,
 843, 94, 115, 860, 79, 0, 891, 157, 0, 0,
 887, 882, 910, 910, 910, 910, 853, 843, 835, 0,
 837, 835, 830, 847, 831, 838, 852, 835, 86, 828,
 829, 839, 0, 106, 910, 0, 76, 92, 829, 829,
 114, 832, 136, 100, 129, 821, 139, 118, 838, 145,
 835, 830, 101, 835, 816, 830, 832, 139, 129, 818,

 0, 822, 141, 817, 813, 811, 813, 817, 61, 150,
 143, 824, 806, 808, 811, 805, 811, 153, 810, 0,
 836, 0, 812, 177, 818, 811, 801, 795, 807, 813,
 805, 808, 827, 824, 793, 802, 797, 786, 801, 782,
 796, 798, 146, 161, 784, 910, 788, 159, 783, 779,
 777, 779, 783, 160, 170, 156, 790, 772, 774, 777,
 771, 777, 173, 776, 774, 774, 777, 768, 778, 0,
 772, 760, 772, 183, 767, 762, 756, 760, 773, 772,
 761, 760, 753, 749, 762, 784, 760, 742, 755, 756,
 749, 748, 753, 738, 741, 744, 747, 749, 734, 746,

 0, 753, 730, 745, 738, 745, 731, 739, 740, 0,
 731, 727, 731, 730, 741, 723, 0, 726, 726, 729,
 720, 730, 910, 724, 712, 724, 723, 718, 713, 707,
 711, 724, 723, 712, 711, 704, 700, 713, 910, 712,
 694, 707, 708, 701, 700, 705, 690, 693, 696, 699,
 701, 686, 720, 689, 210, 694, 689, 682, 0, 715,
 697, 689, 0, 0, 0, 694, 693, 679, 674, 686,
 0, 192, 676, 689, 677, 0, 676, 681, 0, 680,
 690, 678, 677, 667, 675, 682, 664, 659, 660, 173,
 664, 682, 660, 664, 662, 682, 649, 655, 653, 651,

 682, 651, 223, 656, 651, 644, 910, 677, 659, 651,
 910, 910, 910, 656, 655, 641, 636, 648, 910, 196,
 638, 651, 639, 910, 638, 643, 910, 642, 652, 640,
 639, 629, 637, 627, 0, 226, 635, 634, 0, 624,
 628, 628, 624, 623, 629, 623, 615, 621, 615, 607,
 618, 621, 611, 0, 0, 610, 0, 605, 601, 623,
 615, 604, 603, 608, 611, 604, 595, 594, 0, 615,
 606, 605, 623, 604, 592, 583, 591, 910, 599, 598,
 910, 588, 592, 592, 588, 587, 593, 587, 579, 585,
 579, 571, 582, 585, 575, 910, 910, 574, 910, 569,

 565, 587, 573, 578, 214, 599, 570, 576, 561, 559,
 558, 567, 561, 556, 566, 575, 588, 566, 586, 547,
 558, 0, 204, 552, 554, 546, 544, 547, 0, 556,
 555, 547, 555, 551, 534, 539, 549, 535, 0, 541,
 228, 568, 539, 545, 530, 528, 527, 536, 530, 525,
 535, 544, 557, 535, 555, 516, 527, 910, 226, 521,
 520, 516, 531, 517, 527, 198, 515, 519, 518, 525,
 514, 510, 516, 539, 516, 515, 516, 505, 494, 503,
 512, 500, 506, 501, 526, 497, 495, 499, 498, 520,
 500, 495, 485, 484, 0, 0, 0, 485, 503, 0,

 485, 482, 488, 482, 494, 480, 490, 220, 478, 482,
 481, 488, 477, 473, 479, 502, 479, 478, 479, 468,
 457, 466, 475, 463, 469, 464, 489, 460, 458, 462,
 461, 483, 452, 450, 463, 193, 451, 442, 450, 445,
 437, 442, 448, 449, 441, 451, 441, 0, 0, 456,
 0, 0, 452, 436, 440, 445, 440, 426, 429, 429,
 421, 426, 434, 439, 427, 0, 249, 431, 421, 426,
 444, 422, 419, 431, 218, 419, 410, 418, 413, 405,
 410, 416, 417, 409, 419, 409, 910, 910, 424, 910,
 910, 420, 404, 408, 413, 408, 394, 397, 397, 389,

 394, 402, 0, 409, 399, 390, 402, 393, 406, 405,
 394, 397, 390, 381, 396, 0, 380, 386, 395, 384,
 385, 379, 374, 388, 385, 384, 379, 382, 375, 374,
 366, 370, 366, 380, 365, 363, 380, 91, 184, 910,
 194, 198, 213, 219, 234, 237, 228, 234, 229, 222,
 239, 910, 225, 233, 244, 235, 238, 234, 231, 247,
 246, 247, 244, 249, 244, 245, 250, 275, 0, 276,
 0, 259, 260, 244, 0, 258, 259, 0, 0, 251,
 249, 0, 252, 252, 0, 0, 266, 254, 253, 0,
 267, 268, 269, 0, 268, 258, 259, 269, 276, 296,

 0, 298, 910, 299, 910, 282, 283, 267, 910, 281,
 282, 910, 910, 274, 272, 910, 275, 275, 910, 910,
 289, 277, 276, 910, 290, 291, 292, 284, 285, 289,
 290, 293, 0, 0, 287, 294, 287, 0, 0, 0,
 297, 0, 0, 303, 289, 301, 0, 297, 295, 303,
 299, 300, 304, 305, 308, 910, 910, 302, 309, 302,
 910, 910, 910, 312, 910, 910, 353, 312, 313, 306,
 307, 313, 0, 311, 0, 315, 0, 318, 326, 325,
 324, 314, 324, 325, 318, 319, 325, 910, 323, 910,
 327, 328, 329, 330, 340, 341, 334, 0, 335, 344,

 334, 0, 336, 0, 338, 339, 349, 350, 343, 910,
 344, 353, 344, 345, 0, 0, 0, 0, 349, 0,
 345, 348, 349, 910, 910, 910, 910, 910, 0, 0,
 348, 0, 910, 910, 0, 910, 399, 400, 402, 404,
 407
};

static yyconst short int yy_def[842] =
{0,
 836, 1, 836, 837, 836, 836, 838, 839, 836, 836,
 837, 837, 837, 836, 836, 836, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 840, 836,
 836, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 836, 838, 841, 839,
 839, 837, 836, 836, 836, 836, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 840, 836, 31, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,

 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,

 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,

 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 837, 837, 836, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,

 836, 836, 837, 836, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 837, 836, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,

 837, 837, 837, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 837, 836, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,

 836, 836, 837, 836, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,

 837, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 837, 837, 837,
 837, 837, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 837, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 837, 837, 837, 837, 837, 837, 837, 837,

 837, 837, 837, 837, 836, 836, 836, 836, 836, 836,
 836, 836, 837, 837, 837, 837, 837, 837, 837, 837,
 837, 836, 836, 836, 836, 836, 836, 836, 837, 837,
 837, 837, 836, 836, 837, 0, 836, 836, 836, 836,
 836
};

static yyconst short int yy_nxt[970] =
{0,
 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
 14, 15, 16, 17, 4, 18, 19, 20, 4, 21,
 22, 4, 23, 24, 25, 4, 4, 4, 26, 27,
 28, 4, 4, 4, 4, 4, 4, 4, 4, 4,
 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
 4, 4, 4, 4, 4, 4, 4, 29, 30, 31,
 49, 53, 54, 59, 49, 49, 75, 70, 60, 49,
 49, 49, 32, 33, 34, 35, 36, 72, 37, 38,
 71, 39, 63, 73, 40, 41, 64, 42, 43, 44,
 45, 67, 93, 91, 63, 59, 68, 92, 99, 94,

 95, 61, 97, 96, 100, 98, 185, 101, 75, 136,
 103, 186, 116, 137, 102, 105, 49, 49, 104, 117,
 118, 131, 75, 76, 106, 138, 107, 119, 66, 700,
 132, 109, 139, 148, 110, 111, 77, 78, 79, 80,
 81, 149, 82, 83, 71, 84, 121, 112, 85, 86,
 167, 87, 88, 89, 90, 72, 113, 142, 49, 158,
 143, 73, 49, 49, 75, 174, 150, 49, 49, 49,
 114, 145, 175, 159, 146, 151, 154, 152, 161, 155,
 156, 147, 178, 187, 172, 162, 163, 173, 189, 197,
 202, 225, 157, 164, 226, 179, 188, 227, 198, 190,

 231, 242, 203, 240, 228, 238, 204, 205, 206, 250,
 239, 336, 243, 232, 49, 49, 241, 365, 251, 208,
 261, 348, 349, 366, 336, 390, 391, 336, 463, 701,
 487, 538, 464, 488, 489, 465, 702, 466, 606, 539,
 467, 607, 505, 468, 469, 470, 506, 255, 703, 507,
 704, 508, 529, 577, 509, 530, 531, 510, 511, 512,
 303, 578, 633, 642, 705, 706, 643, 634, 707, 708,
 404, 709, 710, 711, 712, 713, 714, 715, 716, 717,
 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
 728, 729, 730, 731, 732, 733, 734, 735, 736, 737,

 738, 739, 740, 741, 742, 743, 744, 745, 746, 747,
 748, 749, 750, 751, 752, 753, 754, 755, 756, 757,
 758, 759, 760, 761, 762, 763, 764, 765, 766, 767,
 768, 769, 770, 771, 772, 773, 774, 775, 776, 777,
 778, 779, 780, 781, 782, 783, 784, 785, 786, 787,
 788, 789, 790, 791, 792, 793, 794, 795, 796, 797,
 798, 799, 800, 801, 802, 803, 804, 805, 806, 807,
 808, 809, 810, 811, 812, 813, 814, 815, 816, 817,
 818, 819, 820, 821, 822, 823, 824, 825, 826, 827,
 767, 828, 829, 830, 831, 832, 833, 834, 835, 46,

 48, 48, 50, 48, 74, 74, 74, 49, 49, 699,
 49, 698, 697, 696, 695, 694, 693, 692, 691, 690,
 689, 688, 687, 686, 685, 684, 683, 682, 681, 680,
 679, 678, 677, 676, 675, 674, 673, 672, 671, 670,
 669, 668, 667, 666, 665, 664, 663, 662, 661, 660,
 659, 658, 657, 656, 655, 654, 653, 652, 651, 650,
 649, 648, 647, 646, 645, 644, 641, 640, 639, 638,
 637, 636, 635, 632, 631, 630, 629, 628, 627, 626,
 625, 624, 623, 622, 621, 620, 619, 618, 617, 616,
 615, 614, 613, 612, 611, 610, 609, 608, 605, 604,

 603, 602, 601, 600, 599, 598, 597, 596, 595, 594,
 593, 592, 591, 590, 589, 588, 587, 586, 585, 584,
 583, 582, 581, 580, 579, 576, 575, 574, 573, 572,
 571, 570, 569, 568, 567, 566, 565, 564, 563, 562,
 561, 560, 559, 558, 557, 556, 555, 554, 553, 552,
 551, 550, 549, 548, 547, 546, 545, 544, 543, 542,
 541, 540, 537, 536, 535, 534, 533, 532, 528, 527,
 526, 525, 524, 523, 522, 521, 520, 519, 518, 517,
 516, 515, 514, 513, 504, 503, 502, 501, 500, 499,
 498, 497, 496, 495, 494, 493, 492, 491, 490, 486,

 485, 484, 483, 482, 481, 480, 479, 478, 477, 476,
 475, 474, 473, 472, 471, 462, 461, 460, 459, 458,
 457, 456, 455, 454, 453, 452, 451, 450, 449, 448,
 447, 446, 445, 444, 443, 442, 441, 440, 439, 438,
 437, 436, 435, 434, 433, 432, 431, 430, 429, 428,
 427, 426, 425, 424, 423, 422, 421, 420, 419, 418,
 417, 416, 415, 414, 413, 412, 411, 410, 409, 408,
 407, 406, 405, 403, 402, 401, 400, 399, 398, 397,
 396, 395, 394, 393, 392, 389, 388, 387, 386, 385,
 384, 383, 382, 381, 380, 379, 378, 377, 376, 375,

 374, 373, 372, 371, 370, 369, 368, 367, 364, 363,
 362, 361, 360, 359, 358, 357, 356, 355, 354, 353,
 352, 351, 350, 347, 346, 345, 344, 343, 342, 341,
 340, 339, 338, 337, 335, 334, 333, 332, 331, 330,
 329, 328, 327, 326, 325, 324, 323, 322, 321, 320,
 319, 318, 317, 316, 315, 314, 313, 312, 311, 310,
 309, 308, 307, 306, 305, 304, 303, 302, 301, 300,
 299, 298, 297, 296, 295, 294, 293, 292, 291, 290,
 289, 288, 287, 286, 285, 284, 283, 282, 281, 280,
 279, 278, 277, 276, 275, 274, 273, 215, 272, 271,

 270, 269, 268, 267, 266, 265, 264, 263, 262, 260,
 259, 258, 257, 256, 255, 254, 253, 252, 249, 248,
 247, 246, 245, 244, 237, 236, 235, 234, 233, 230,
 229, 224, 223, 222, 221, 220, 219, 218, 217, 216,
 215, 214, 213, 212, 211, 210, 209, 208, 207, 201,
 200, 199, 196, 195, 194, 193, 192, 191, 184, 183,
 182, 181, 180, 177, 176, 171, 170, 169, 168, 166,
 165, 160, 153, 144, 141, 140, 135, 134, 133, 130,
 129, 128, 127, 126, 125, 124, 123, 122, 121, 120,
 52, 51, 47, 115, 108, 69, 66, 65, 62, 61,

 58, 57, 56, 55, 52, 52, 51, 47, 836, 3,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836
};

static yyconst short int yy_chk[970] =
{0,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
 7, 14, 14, 19, 7, 7, 29, 27, 19, 7,
 7, 7, 2, 2, 2, 2, 2, 28, 2, 2,
 27, 2, 22, 28, 2, 2, 22, 2, 2, 2,
 2, 25, 33, 32, 37, 34, 25, 32, 37, 33,

 34, 35, 36, 35, 38, 36, 109, 38, 74, 77,
 39, 109, 45, 77, 38, 40, 7, 7, 39, 45,
 45, 69, 29, 31, 40, 78, 40, 45, 39, 638,
 69, 42, 78, 84, 42, 42, 31, 31, 31, 31,
 31, 84, 31, 31, 42, 31, 93, 42, 31, 31,
 93, 31, 31, 31, 31, 43, 43, 81, 48, 88,
 81, 43, 48, 48, 74, 99, 85, 48, 48, 48,
 43, 83, 99, 88, 83, 85, 87, 85, 90, 87,
 87, 83, 103, 110, 98, 90, 90, 98, 111, 118,
 124, 143, 87, 90, 143, 103, 110, 144, 118, 111,

 148, 156, 124, 155, 144, 154, 124, 124, 124, 163,
 154, 255, 156, 148, 48, 48, 155, 290, 163, 174,
 174, 272, 272, 290, 303, 320, 320, 336, 405, 639,
 423, 466, 405, 423, 423, 405, 641, 405, 536, 466,
 405, 536, 441, 405, 405, 405, 441, 255, 642, 441,
 643, 441, 459, 508, 441, 459, 459, 441, 441, 441,
 303, 508, 567, 575, 644, 645, 575, 567, 646, 647,
 336, 648, 649, 650, 651, 653, 654, 655, 656, 657,
 658, 659, 660, 661, 662, 663, 664, 665, 666, 667,
 668, 670, 672, 673, 674, 676, 677, 680, 681, 683,

 684, 687, 688, 689, 691, 692, 693, 695, 696, 697,
 698, 699, 700, 702, 704, 706, 707, 708, 710, 711,
 714, 715, 717, 718, 721, 722, 723, 725, 726, 727,
 728, 729, 730, 731, 732, 735, 736, 737, 741, 744,
 745, 746, 748, 749, 750, 751, 752, 753, 754, 755,
 758, 759, 760, 764, 767, 768, 769, 770, 771, 772,
 774, 776, 778, 779, 780, 781, 782, 783, 784, 785,
 786, 787, 789, 791, 792, 793, 794, 795, 796, 797,
 799, 800, 801, 803, 805, 806, 807, 808, 809, 811,
 767, 812, 813, 814, 819, 821, 822, 823, 831, 837,

 838, 838, 839, 838, 840, 840, 840, 841, 841, 637,
 841, 636, 635, 634, 633, 632, 631, 630, 629, 628,
 627, 626, 625, 624, 623, 622, 621, 620, 619, 618,
 617, 615, 614, 613, 612, 611, 610, 609, 608, 607,
 606, 605, 604, 602, 601, 600, 599, 598, 597, 596,
 595, 594, 593, 592, 589, 586, 585, 584, 583, 582,
 581, 580, 579, 578, 577, 576, 574, 573, 572, 571,
 570, 569, 568, 565, 564, 563, 562, 561, 560, 559,
 558, 557, 556, 555, 554, 553, 550, 547, 546, 545,
 544, 543, 542, 541, 540, 539, 538, 537, 535, 534,

 533, 532, 531, 530, 529, 528, 527, 526, 525, 524,
 523, 522, 521, 520, 519, 518, 517, 516, 515, 514,
 513, 512, 511, 510, 509, 507, 506, 505, 504, 503,
 502, 501, 499, 498, 494, 493, 492, 491, 490, 489,
 488, 487, 486, 485, 484, 483, 482, 481, 480, 479,
 478, 477, 476, 475, 474, 473, 472, 471, 470, 469,
 468, 467, 465, 464, 463, 462, 461, 460, 457, 456,
 455, 454, 453, 452, 451, 450, 449, 448, 447, 446,
 445, 444, 443, 442, 440, 438, 437, 436, 435, 434,
 433, 432, 431, 430, 428, 427, 426, 425, 424, 421,

 420, 419, 418, 417, 416, 415, 414, 413, 412, 411,
 410, 409, 408, 407, 406, 404, 403, 402, 401, 400,
 398, 395, 394, 393, 392, 391, 390, 389, 388, 387,
 386, 385, 384, 383, 382, 380, 379, 377, 376, 375,
 374, 373, 372, 371, 370, 368, 367, 366, 365, 364,
 363, 362, 361, 360, 359, 358, 356, 353, 352, 351,
 350, 349, 348, 347, 346, 345, 344, 343, 342, 341,
 340, 338, 337, 334, 333, 332, 331, 330, 329, 328,
 326, 325, 323, 322, 321, 318, 317, 316, 315, 314,
 310, 309, 308, 306, 305, 304, 302, 301, 300, 299,

 298, 297, 296, 295, 294, 293, 292, 291, 289, 288,
 287, 286, 285, 284, 283, 282, 281, 280, 278, 277,
 275, 274, 273, 270, 269, 268, 267, 266, 262, 261,
 260, 258, 257, 256, 254, 253, 252, 251, 250, 249,
 248, 247, 246, 245, 244, 243, 242, 241, 240, 238,
 237, 236, 235, 234, 233, 232, 231, 230, 229, 228,
 227, 226, 225, 224, 222, 221, 220, 219, 218, 216,
 215, 214, 213, 212, 211, 209, 208, 207, 206, 205,
 204, 203, 202, 200, 199, 198, 197, 196, 195, 194,
 193, 192, 191, 190, 189, 188, 187, 186, 185, 184,

 183, 182, 181, 180, 179, 178, 177, 176, 175, 173,
 172, 171, 169, 168, 167, 166, 165, 164, 162, 161,
 160, 159, 158, 157, 153, 152, 151, 150, 149, 147,
 145, 142, 141, 140, 139, 138, 137, 136, 135, 134,
 133, 132, 131, 130, 129, 128, 127, 126, 125, 123,
 121, 119, 117, 116, 115, 114, 113, 112, 108, 107,
 106, 105, 104, 102, 100, 97, 96, 95, 94, 92,
 91, 89, 86, 82, 80, 79, 72, 71, 70, 68,
 67, 66, 65, 64, 63, 62, 61, 59, 58, 57,
 52, 51, 47, 44, 41, 26, 24, 23, 21, 20,

 18, 17, 16, 15, 12, 11, 8, 5, 3, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836, 836,
 836, 836, 836, 836, 836, 836, 836, 836, 836
};

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Compiler/lexin"
#define INITIAL 0
#line 2 "Compiler/lexin"
#include "y.tab.h"
#include "types.h"

int numligne = 1;
#line 858 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO ((void));
#else
extern int yywrap YY_PROTO ((void));
#endif
#endif

#ifndef YY_NO_UNPUT
void yyunput YY_PROTO ((int c, char *buf_ptr));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO ((char *, yyconst char *, int));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO ((yyconst char *));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO ((void));
#else
static int input YY_PROTO ((void));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO ((int new_state));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO ((void));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO ((void));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
{
  register yy_state_type yy_current_state;
  register char *yy_cp = NULL, *yy_bp = NULL;
  register int yy_act;

#line 23 "Compiler/lexin"

#line 1014 "lex.yy.c"

  if (yy_init)
    {
      yy_init = 0;

#ifdef YY_USER_INIT
      YY_USER_INIT;
#endif

      if (!yy_start)
	yy_start = 1;		/* first start state */

      if (!yyin)
	yyin = stdin;

      if (!yyout)
	yyout = stdout;

      if (!yy_current_buffer)
	yy_current_buffer =
	  yy_create_buffer (yyin, YY_BUF_SIZE);

      yy_load_buffer_state ();
    }

  while (1)			/* loops until end-of-file is reached */
    {
      yy_cp = yy_c_buf_p;

      /* Support of yytext. */
      *yy_cp = yy_hold_char;

      /* yy_bp points to the position in yy_ch_buf of the start of
       * the current run.
       */
      yy_bp = yy_cp;

      yy_current_state = yy_start;
      yy_current_state += YY_AT_BOL ();
    yy_match:
      do
	{
	  register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI (*yy_cp)];
	  if (yy_accept[yy_current_state])
	    {
	      yy_last_accepting_state = yy_current_state;
	      yy_last_accepting_cpos = yy_cp;
	    }
	  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	    {
	      yy_current_state = (int) yy_def[yy_current_state];
	      if (yy_current_state >= 837)
		yy_c = yy_meta[(unsigned int) yy_c];
	    }
	  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	  ++yy_cp;
	}
      while (yy_base[yy_current_state] != 910);

    yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if (yy_act == 0)
	{			/* have to back up */
	  yy_cp = yy_last_accepting_cpos;
	  yy_current_state = yy_last_accepting_state;
	  yy_act = yy_accept[yy_current_state];
	}

      YY_DO_BEFORE_ACTION;


    do_action:			/* This label is used only to access EOF actions. */


      switch (yy_act)
	{			/* beginning of action switch */
	case 0:		/* must back up */
	  /* undo the effects of YY_DO_BEFORE_ACTION */
	  *yy_cp = yy_hold_char;
	  yy_cp = yy_last_accepting_cpos;
	  yy_current_state = yy_last_accepting_state;
	  goto yy_find_action;

	case 1:
	  YY_RULE_SETUP
#line 24 "Compiler/lexin"
	    ;
	  YY_BREAK
	case 2:
	  YY_RULE_SETUP
#line 25 "Compiler/lexin"
	    ;
	  YY_BREAK
	case 3:
	  YY_RULE_SETUP
#line 27 "Compiler/lexin"
	  {
	    return WINDOWTITLE;
	  }
	  YY_BREAK
	case 4:
	  YY_RULE_SETUP
#line 28 "Compiler/lexin"
	  {
	    return WINDOWSIZE;
	  }
	  YY_BREAK
	case 5:
	  YY_RULE_SETUP
#line 29 "Compiler/lexin"
	  {
	    return WINDOWPOSITION;
	  }
	  YY_BREAK
	case 6:
	  YY_RULE_SETUP
#line 30 "Compiler/lexin"
	  {
	    return FORECOLOR;
	  }
	  YY_BREAK
	case 7:
	  YY_RULE_SETUP
#line 31 "Compiler/lexin"
	  {
	    return BACKCOLOR;
	  }
	  YY_BREAK
	case 8:
	  YY_RULE_SETUP
#line 32 "Compiler/lexin"
	  {
	    return SHADCOLOR;
	  }
	  YY_BREAK
	case 9:
	  YY_RULE_SETUP
#line 33 "Compiler/lexin"
	  {
	    return LICOLOR;
	  }
	  YY_BREAK
	case 10:
	  YY_RULE_SETUP
#line 34 "Compiler/lexin"
	  {
	    return OBJECT;
	  }
	  YY_BREAK
	case 11:
	  YY_RULE_SETUP
#line 35 "Compiler/lexin"
	  {
	    return PROP;
	  }
	  YY_BREAK
	case 12:
	  YY_RULE_SETUP
#line 36 "Compiler/lexin"
	  {
	    return MAIN;
	  }
	  YY_BREAK
	case 13:
	  YY_RULE_SETUP
#line 37 "Compiler/lexin"
	  {
	    return END;
	  }
	  YY_BREAK
	case 14:
	  YY_RULE_SETUP
#line 38 "Compiler/lexin"
	  {
	    return FONT;
	  }
	  YY_BREAK
	case 15:
	  YY_RULE_SETUP
#line 40 "Compiler/lexin"
	  {
	    return TYPE;
	  }
	  YY_BREAK
	case 16:
	  YY_RULE_SETUP
#line 41 "Compiler/lexin"
	  {
	    return SIZE;
	  }
	  YY_BREAK
	case 17:
	  YY_RULE_SETUP
#line 42 "Compiler/lexin"
	  {
	    return POSITION;
	  }
	  YY_BREAK
	case 18:
	  YY_RULE_SETUP
#line 43 "Compiler/lexin"
	  {
	    return VALUE;
	  }
	  YY_BREAK
	case 19:
	  YY_RULE_SETUP
#line 44 "Compiler/lexin"
	  {
	    return VALUEMIN;
	  }
	  YY_BREAK
	case 20:
	  YY_RULE_SETUP
#line 45 "Compiler/lexin"
	  {
	    return VALUEMAX;
	  }
	  YY_BREAK
	case 21:
	  YY_RULE_SETUP
#line 46 "Compiler/lexin"
	  {
	    return TITLE;
	  }
	  YY_BREAK
	case 22:
	  YY_RULE_SETUP
#line 47 "Compiler/lexin"
	  {
	    return SWALLOWEXEC;
	  }
	  YY_BREAK
	case 23:
	  YY_RULE_SETUP
#line 48 "Compiler/lexin"
	  {
	    return ICON;
	  }
	  YY_BREAK
	case 24:
	  YY_RULE_SETUP
#line 49 "Compiler/lexin"
	  {
	    return FLAGS;
	  }
	  YY_BREAK
	case 25:
	  YY_RULE_SETUP
#line 50 "Compiler/lexin"
	  {
	    return HIDDEN;
	  }
	  YY_BREAK
	case 26:
	  YY_RULE_SETUP
#line 51 "Compiler/lexin"
	  {
	    return CANBESELECTED;
	  }
	  YY_BREAK
	case 27:
	  YY_RULE_SETUP
#line 52 "Compiler/lexin"
	  {
	    return NORELIEFSTRING;
	  }
	  YY_BREAK
	case 28:
	  YY_RULE_SETUP
#line 54 "Compiler/lexin"
	  {
	    return EXEC;
	  }
	  YY_BREAK
	case 29:
	  YY_RULE_SETUP
#line 55 "Compiler/lexin"
	  {
	    return HIDE;
	  }
	  YY_BREAK
	case 30:
	  YY_RULE_SETUP
#line 56 "Compiler/lexin"
	  {
	    return SHOW;
	  }
	  YY_BREAK
	case 31:
	  YY_RULE_SETUP
#line 57 "Compiler/lexin"
	  {
	    return CHVALUE;
	  }
	  YY_BREAK
	case 32:
	  YY_RULE_SETUP
#line 58 "Compiler/lexin"
	  {
	    return CHVALUEMAX;
	  }
	  YY_BREAK
	case 33:
	  YY_RULE_SETUP
#line 59 "Compiler/lexin"
	  {
	    return CHVALUEMIN;
	  }
	  YY_BREAK
	case 34:
	  YY_RULE_SETUP
#line 60 "Compiler/lexin"
	  {
	    return GETTITLE;
	  }
	  YY_BREAK
	case 35:
	  YY_RULE_SETUP
#line 61 "Compiler/lexin"
	  {
	    return GETVALUE;
	  }
	  YY_BREAK
	case 36:
	  YY_RULE_SETUP
#line 62 "Compiler/lexin"
	  {
	    return GETOUTPUT;
	  }
	  YY_BREAK
	case 37:
	  YY_RULE_SETUP
#line 63 "Compiler/lexin"
	  {
	    return GETASOPTION;
	  }
	  YY_BREAK
	case 38:
	  YY_RULE_SETUP
#line 64 "Compiler/lexin"
	  {
	    return SETASOPTION;
	  }
	  YY_BREAK
	case 39:
	  YY_RULE_SETUP
#line 65 "Compiler/lexin"
	  {
	    return NUMTOHEX;
	  }
	  YY_BREAK
	case 40:
	  YY_RULE_SETUP
#line 66 "Compiler/lexin"
	  {
	    return HEXTONUM;
	  }
	  YY_BREAK
	case 41:
	  YY_RULE_SETUP
#line 67 "Compiler/lexin"
	  {
	    return ADD;
	  }
	  YY_BREAK
	case 42:
	  YY_RULE_SETUP
#line 68 "Compiler/lexin"
	  {
	    return MULT;
	  }
	  YY_BREAK
	case 43:
	  YY_RULE_SETUP
#line 69 "Compiler/lexin"
	  {
	    return DIV;
	  }
	  YY_BREAK
	case 44:
	  YY_RULE_SETUP
#line 70 "Compiler/lexin"
	  {
	    return STRCOPY;
	  }
	  YY_BREAK
	case 45:
	  YY_RULE_SETUP
#line 71 "Compiler/lexin"
	  {
	    return LAUNCHSCRIPT;
	  }
	  YY_BREAK
	case 46:
	  YY_RULE_SETUP
#line 72 "Compiler/lexin"
	  {
	    return GETSCRIPTFATHER;
	  }
	  YY_BREAK
	case 47:
	  YY_RULE_SETUP
#line 73 "Compiler/lexin"
	  {
	    return RECEIVFROMSCRIPT;
	  }
	  YY_BREAK
	case 48:
	  YY_RULE_SETUP
#line 74 "Compiler/lexin"
	  {
	    return REMAINDEROFDIV;
	  }
	  YY_BREAK
	case 49:
	  YY_RULE_SETUP
#line 75 "Compiler/lexin"
	  {
	    return GETTIME;
	  }
	  YY_BREAK
	case 50:
	  YY_RULE_SETUP
#line 76 "Compiler/lexin"
	  {
	    return GETSCRIPTARG;
	  }
	  YY_BREAK
	case 51:
	  YY_RULE_SETUP
#line 77 "Compiler/lexin"
	  {
	    return POSITION;
	  }
	  YY_BREAK
	case 52:
	  YY_RULE_SETUP
#line 78 "Compiler/lexin"
	  {
	    return SIZE;
	  }
	  YY_BREAK
	case 53:
	  YY_RULE_SETUP
#line 79 "Compiler/lexin"
	  {
	    return TITLE;
	  }
	  YY_BREAK
	case 54:
	  YY_RULE_SETUP
#line 80 "Compiler/lexin"
	  {
	    return ICON;
	  }
	  YY_BREAK
	case 55:
	  YY_RULE_SETUP
#line 81 "Compiler/lexin"
	  {
	    return FONT;
	  }
	  YY_BREAK
	case 56:
	  YY_RULE_SETUP
#line 82 "Compiler/lexin"
	  {
	    return CHFORECOLOR;
	  }
	  YY_BREAK
	case 57:
	  YY_RULE_SETUP
#line 83 "Compiler/lexin"
	  {
	    return CHBACKCOLOR;
	  }
	  YY_BREAK
	case 58:
	  YY_RULE_SETUP
#line 84 "Compiler/lexin"
	  {
	    return SET;
	  }
	  YY_BREAK
	case 59:
	  YY_RULE_SETUP
#line 85 "Compiler/lexin"
	  {
	    return SENDSIGN;
	  }
	  YY_BREAK
	case 60:
	  YY_RULE_SETUP
#line 86 "Compiler/lexin"
	  {
	    return QUIT;
	  }
	  YY_BREAK
	case 61:
	  YY_RULE_SETUP
#line 87 "Compiler/lexin"
	  {
	    return INIT;
	  }
	  YY_BREAK
	case 62:
	  YY_RULE_SETUP
#line 88 "Compiler/lexin"
	  {
	    return PERIODICTASK;
	  }
	  YY_BREAK
	case 63:
	  YY_RULE_SETUP
#line 89 "Compiler/lexin"
	  {
	    return FOR;
	  }
	  YY_BREAK
	case 64:
	  YY_RULE_SETUP
#line 90 "Compiler/lexin"
	  {
	    return WARP;
	  }
	  YY_BREAK
	case 65:
	  YY_RULE_SETUP
#line 91 "Compiler/lexin"
	  {
	    return WRITETOFILE;
	  }
	  YY_BREAK
	case 66:
	  YY_RULE_SETUP
#line 92 "Compiler/lexin"
	  {
	    return SENDTOSCRIPT;
	  }
	  YY_BREAK
	case 67:
	  YY_RULE_SETUP
#line 93 "Compiler/lexin"
	  {
	    return SINGLECLIC;
	  }
	  YY_BREAK
	case 68:
	  YY_RULE_SETUP
#line 94 "Compiler/lexin"
	  {
	    return DOUBLECLIC;
	  }
	  YY_BREAK
	case 69:
	  YY_RULE_SETUP
#line 95 "Compiler/lexin"
	  {
	    return TO;
	  }
	  YY_BREAK
	case 70:
	  YY_RULE_SETUP
#line 96 "Compiler/lexin"
	  {
	    return DO;
	  }
	  YY_BREAK
	case 71:
	  YY_RULE_SETUP
#line 97 "Compiler/lexin"
	  {
	    return IF;
	  }
	  YY_BREAK
	case 72:
	  YY_RULE_SETUP
#line 98 "Compiler/lexin"
	  {
	    return THEN;
	  }
	  YY_BREAK
	case 73:
	  YY_RULE_SETUP
#line 99 "Compiler/lexin"
	  {
	    return ELSE;
	  }
	  YY_BREAK
	case 74:
	  YY_RULE_SETUP
#line 101 "Compiler/lexin"
	  {
	    return INF;
	  }
	  YY_BREAK
	case 75:
	  YY_RULE_SETUP
#line 102 "Compiler/lexin"
	  {
	    return INFEQ;
	  }
	  YY_BREAK
	case 76:
	  YY_RULE_SETUP
#line 103 "Compiler/lexin"
	  {
	    return SUPEQ;
	  }
	  YY_BREAK
	case 77:
	  YY_RULE_SETUP
#line 104 "Compiler/lexin"
	  {
	    return SUP;
	  }
	  YY_BREAK
	case 78:
	  YY_RULE_SETUP
#line 105 "Compiler/lexin"
	  {
	    return DIFF;
	  }
	  YY_BREAK
	case 79:
	  YY_RULE_SETUP
#line 106 "Compiler/lexin"
	  {
	    return EQUAL;
	  }
	  YY_BREAK
	case 80:
	  YY_RULE_SETUP
#line 107 "Compiler/lexin"
	  {
	    return GET;
	  }
	  YY_BREAK
	case 81:
	  YY_RULE_SETUP
#line 109 "Compiler/lexin"
	  {
	    return WHILE;
	  }
	  YY_BREAK
	case 82:
	  YY_RULE_SETUP
#line 110 "Compiler/lexin"
	  {
	    return CASE;
	  }
	  YY_BREAK
	case 83:
	  YY_RULE_SETUP
#line 111 "Compiler/lexin"
	  {
	    return BEG;
	  }
	  YY_BREAK
	case 84:
	  YY_RULE_SETUP
#line 112 "Compiler/lexin"
	  {
	    return POINT;
	  }
	  YY_BREAK
	case 85:
	  YY_RULE_SETUP
#line 113 "Compiler/lexin"
	  {
	    return BEGF;
	  }
	  YY_BREAK
	case 86:
	  YY_RULE_SETUP
#line 114 "Compiler/lexin"
	  {
	    return ENDF;
	  }
	  YY_BREAK
	case 87:
	  YY_RULE_SETUP
#line 117 "Compiler/lexin"
	  {
	    yylval.number = atoi (yytext);
	    return NUMBER;
	  }
	  YY_BREAK
	case 88:
	  YY_RULE_SETUP
#line 121 "Compiler/lexin"
	  {
	    yylval.str = (char *) strdup (yytext + 1);
	    yylval.str[yyleng - 1] = '\0';
	    return VAR;
	  }
	  YY_BREAK
	case 89:
	  YY_RULE_SETUP
#line 126 "Compiler/lexin"
	  {			/* Str entre "" */
	    yylval.str = (char *) strdup (yytext + 1);
	    yylval.str[yyleng - 2] = '\0';
	    return GSTR;
	  }
	  YY_BREAK
	case 90:
	  YY_RULE_SETUP
#line 132 "Compiler/lexin"
	  {
	    yylval.str = (char *) strdup (yytext);
	    yylval.str[yyleng] = '\0';
	    return STR;
	  }
	  YY_BREAK
	case 91:
	  YY_RULE_SETUP
#line 138 "Compiler/lexin"
	  {
	    numligne++;
	  }
	  YY_BREAK
	case 92:
	  YY_RULE_SETUP
#line 155 "Compiler/lexin"
	    ECHO;
	  YY_BREAK
#line 1571 "lex.yy.c"
	case YY_STATE_EOF (INITIAL):
	  yyterminate ();

	case YY_END_OF_BUFFER:
	  {
	    /* Amount of text matched not including the EOB char. */
	    int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

	    /* Undo the effects of YY_DO_BEFORE_ACTION. */
	    *yy_cp = yy_hold_char;
	    YY_RESTORE_YY_MORE_OFFSET

	      if (yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW)
	      {
		/* We're scanning a new file or input source.  It's
		 * possible that this happened because the user
		 * just pointed yyin at a new source and called
		 * yylex().  If so, then we have to assure
		 * consistency between yy_current_buffer and our
		 * globals.  Here is the right place to do so, because
		 * this is the first action (other than possibly a
		 * back-up) that will match for the new input source.
		 */
		yy_n_chars = yy_current_buffer->yy_n_chars;
		yy_current_buffer->yy_input_file = yyin;
		yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
	      }

	    /* Note that here we test for yy_c_buf_p "<=" to the position
	     * of the first EOB in the buffer, since yy_c_buf_p will
	     * already have been incremented past the NUL character
	     * (since all states make transitions on EOB to the
	     * end-of-buffer state).  Contrast this with the test
	     * in input().
	     */
	    if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars])
	      {			/* This was really a NUL. */
		yy_state_type yy_next_state;

		yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

		yy_current_state = yy_get_previous_state ();

		/* Okay, we're now positioned to make the NUL
		 * transition.  We couldn't have
		 * yy_get_previous_state() go ahead and do it
		 * for us because it doesn't know how to deal
		 * with the possibility of jamming (and we don't
		 * want to build jamming into it because then it
		 * will run more slowly).
		 */

		yy_next_state = yy_try_NUL_trans (yy_current_state);

		yy_bp = yytext_ptr + YY_MORE_ADJ;

		if (yy_next_state)
		  {
		    /* Consume the NUL. */
		    yy_cp = ++yy_c_buf_p;
		    yy_current_state = yy_next_state;
		    goto yy_match;
		  }

		else
		  {
		    yy_cp = yy_c_buf_p;
		    goto yy_find_action;
		  }
	      }

	    else
	      switch (yy_get_next_buffer ())
		{
		case EOB_ACT_END_OF_FILE:
		  {
		    yy_did_buffer_switch_on_eof = 0;

		    if (yywrap ())
		      {
			/* Note: because we've taken care in
			 * yy_get_next_buffer() to have set up
			 * yytext, we can now set up
			 * yy_c_buf_p so that if some total
			 * hoser (like flex itself) wants to
			 * call the scanner after we return the
			 * YY_NULL, it'll still work - another
			 * YY_NULL will get returned.
			 */
			yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

			yy_act = YY_STATE_EOF (YY_START);
			goto do_action;
		      }

		    else
		      {
			if (!yy_did_buffer_switch_on_eof)
			  YY_NEW_FILE;
		      }
		    break;
		  }

		case EOB_ACT_CONTINUE_SCAN:
		  yy_c_buf_p =
		    yytext_ptr + yy_amount_of_matched_text;

		  yy_current_state = yy_get_previous_state ();

		  yy_cp = yy_c_buf_p;
		  yy_bp = yytext_ptr + YY_MORE_ADJ;
		  goto yy_match;

		case EOB_ACT_LAST_MATCH:
		  yy_c_buf_p =
		    &yy_current_buffer->yy_ch_buf[yy_n_chars];

		  yy_current_state = yy_get_previous_state ();

		  yy_cp = yy_c_buf_p;
		  yy_bp = yytext_ptr + YY_MORE_ADJ;
		  goto yy_find_action;
		}
	    break;
	  }

	default:
	  YY_FATAL_ERROR (
		      "fatal flex scanner internal error--no action found");
	}			/* end of action switch */
    }				/* end of scanning one token */
}				/* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer

 * Returns a code representing an action:
 *      EOB_ACT_LAST_MATCH -
 *      EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *      EOB_ACT_END_OF_FILE - end of file
 */

static int
yy_get_next_buffer ()
{
  register char *dest = yy_current_buffer->yy_ch_buf;
  register char *source = yytext_ptr;
  register int number_to_move, i;
  int ret_val;

  if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1])
    YY_FATAL_ERROR (
		 "fatal flex scanner internal error--end of buffer missed");

  if (yy_current_buffer->yy_fill_buffer == 0)
    {				/* Don't try to fill the buffer, so this is an EOF. */
      if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1)
	{
	  /* We matched a single character, the EOB, so
	   * treat this as a final EOF.
	   */
	  return EOB_ACT_END_OF_FILE;
	}

      else
	{
	  /* We matched some text prior to the EOB, first
	   * process it.
	   */
	  return EOB_ACT_LAST_MATCH;
	}
    }

  /* Try to read more data. */

  /* First move last chars to start of buffer. */
  number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

  for (i = 0; i < number_to_move; ++i)
    *(dest++) = *(source++);

  if (yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING)
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
    yy_current_buffer->yy_n_chars = yy_n_chars = 0;

  else
    {
      int num_to_read =
      yy_current_buffer->yy_buf_size - number_to_move - 1;

      while (num_to_read <= 0)
	{			/* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
	  YY_FATAL_ERROR (
			   "input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

	  /* just a shorter name for the current buffer */
	  YY_BUFFER_STATE b = yy_current_buffer;

	  int yy_c_buf_p_offset =
	  (int) (yy_c_buf_p - b->yy_ch_buf);

	  if (b->yy_is_our_buffer)
	    {
	      int new_size = b->yy_buf_size * 2;

	      if (new_size <= 0)
		b->yy_buf_size += b->yy_buf_size / 8;
	      else
		b->yy_buf_size *= 2;

	      b->yy_ch_buf = (char *)
	      /* Include room in for 2 EOB chars. */
		yy_flex_realloc ((void *) b->yy_ch_buf,
				 b->yy_buf_size + 2);
	    }
	  else
	    /* Can't grow it, we don't own it. */
	    b->yy_ch_buf = 0;

	  if (!b->yy_ch_buf)
	    YY_FATAL_ERROR (
			     "fatal error - scanner input buffer overflow");

	  yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

	  num_to_read = yy_current_buffer->yy_buf_size -
	    number_to_move - 1;
#endif
	}

      if (num_to_read > YY_READ_BUF_SIZE)
	num_to_read = YY_READ_BUF_SIZE;

      /* Read in more data. */
      YY_INPUT ((&yy_current_buffer->yy_ch_buf[number_to_move]),
		yy_n_chars, num_to_read);

      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  if (yy_n_chars == 0)
    {
      if (number_to_move == YY_MORE_ADJ)
	{
	  ret_val = EOB_ACT_END_OF_FILE;
	  yyrestart (yyin);
	}

      else
	{
	  ret_val = EOB_ACT_LAST_MATCH;
	  yy_current_buffer->yy_buffer_status =
	    YY_BUFFER_EOF_PENDING;
	}
    }

  else
    ret_val = EOB_ACT_CONTINUE_SCAN;

  yy_n_chars += number_to_move;
  yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
  yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

  yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

  return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type
yy_get_previous_state ()
{
  register yy_state_type yy_current_state;
  register char *yy_cp;

  yy_current_state = yy_start;
  yy_current_state += YY_AT_BOL ();

  for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp)
    {
      register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI (*yy_cp)] : 1);
      if (yy_accept[yy_current_state])
	{
	  yy_last_accepting_state = yy_current_state;
	  yy_last_accepting_cpos = yy_cp;
	}
      while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	{
	  yy_current_state = (int) yy_def[yy_current_state];
	  if (yy_current_state >= 837)
	    yy_c = yy_meta[(unsigned int) yy_c];
	}
      yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    }

  return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character

 * synopsis
 *      next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type
yy_try_NUL_trans (yy_state_type yy_current_state)
#else
static yy_state_type
yy_try_NUL_trans (yy_current_state)
     yy_state_type yy_current_state;
#endif
{
  register int yy_is_jam;
  register char *yy_cp = yy_c_buf_p;

  register YY_CHAR yy_c = 1;
  if (yy_accept[yy_current_state])
    {
      yy_last_accepting_state = yy_current_state;
      yy_last_accepting_cpos = yy_cp;
    }
  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
      yy_current_state = (int) yy_def[yy_current_state];
      if (yy_current_state >= 837)
	yy_c = yy_meta[(unsigned int) yy_c];
    }
  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
  yy_is_jam = (yy_current_state == 836);

  return yy_is_jam ? 0 : yy_current_state;
}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
void
yyunput (int c, register char *yy_bp)
#else
void
yyunput (c, yy_bp)
     int c;
     register char *yy_bp;
#endif
{
  register char *yy_cp = yy_c_buf_p;

  /* undo effects of setting up yytext */
  *yy_cp = yy_hold_char;

  if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
    {				/* need to shift things up to make room */
      /* +2 for EOB chars. */
      register int number_to_move = yy_n_chars + 2;
      register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
      register char *source =
      &yy_current_buffer->yy_ch_buf[number_to_move];

      while (source > yy_current_buffer->yy_ch_buf)
	*--dest = *--source;

      yy_cp += (int) (dest - source);
      yy_bp += (int) (dest - source);
      yy_current_buffer->yy_n_chars =
	yy_n_chars = yy_current_buffer->yy_buf_size;

      if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
	YY_FATAL_ERROR ("flex scanner push-back overflow");
    }

  *--yy_cp = (char) c;


  yytext_ptr = yy_bp;
  yy_hold_char = *yy_cp;
  yy_c_buf_p = yy_cp;
}
#endif /* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int
yyinput ()
#else
static int
input ()
#endif
{
  int c;

  *yy_c_buf_p = yy_hold_char;

  if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR)
    {
      /* yy_c_buf_p now points to the character we want to return.
       * If this occurs *before* the EOB characters, then it's a
       * valid NUL; if not, then we've hit the end of the buffer.
       */
      if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
	/* This was really a NUL. */
	*yy_c_buf_p = '\0';

      else
	{			/* need more input */
	  int offset = yy_c_buf_p - yytext_ptr;
	  ++yy_c_buf_p;

	  switch (yy_get_next_buffer ())
	    {
	    case EOB_ACT_LAST_MATCH:
	      /* This happens because yy_g_n_b()
	       * sees that we've accumulated a
	       * token and flags that we need to
	       * try matching the token before
	       * proceeding.  But for input(),
	       * there's no matching to consider.
	       * So convert the EOB_ACT_LAST_MATCH
	       * to EOB_ACT_END_OF_FILE.
	       */

	      /* Reset buffer status. */
	      yyrestart (yyin);

	      /* fall through */

	    case EOB_ACT_END_OF_FILE:
	      {
		if (yywrap ())
		  return EOF;

		if (!yy_did_buffer_switch_on_eof)
		  YY_NEW_FILE;
#ifdef __cplusplus
		return yyinput ();
#else
		return input ();
#endif
	      }

	    case EOB_ACT_CONTINUE_SCAN:
	      yy_c_buf_p = yytext_ptr + offset;
	      break;
	    }
	}
    }

  c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
  *yy_c_buf_p = '\0';		/* preserve yytext */
  yy_hold_char = *++yy_c_buf_p;

  yy_current_buffer->yy_at_bol = (c == '\n');

  return c;
}


#ifdef YY_USE_PROTOS
void
yyrestart (FILE * input_file)
#else
void
yyrestart (input_file)
     FILE *input_file;
#endif
{
  if (!yy_current_buffer)
    yy_current_buffer = yy_create_buffer (yyin, YY_BUF_SIZE);

  yy_init_buffer (yy_current_buffer, input_file);
  yy_load_buffer_state ();
}


#ifdef YY_USE_PROTOS
void
yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
#else
void
yy_switch_to_buffer (new_buffer)
     YY_BUFFER_STATE new_buffer;
#endif
{
  if (yy_current_buffer == new_buffer)
    return;

  if (yy_current_buffer)
    {
      /* Flush out information for old buffer. */
      *yy_c_buf_p = yy_hold_char;
      yy_current_buffer->yy_buf_pos = yy_c_buf_p;
      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  yy_current_buffer = new_buffer;
  yy_load_buffer_state ();

  /* We don't actually know whether we did this switch during
   * EOF (yywrap()) processing, but the only time this flag
   * is looked at is after yywrap() is called, so it's safe
   * to go ahead and always set it.
   */
  yy_did_buffer_switch_on_eof = 1;
}


#ifdef YY_USE_PROTOS
void
yy_load_buffer_state (void)
#else
void
yy_load_buffer_state ()
#endif
{
  yy_n_chars = yy_current_buffer->yy_n_chars;
  yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
  yyin = yy_current_buffer->yy_input_file;
  yy_hold_char = *yy_c_buf_p;
}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_create_buffer (FILE * file, int size)
#else
YY_BUFFER_STATE
yy_create_buffer (file, size)
     FILE *file;
     int size;
#endif
{
  YY_BUFFER_STATE b;

  b = (YY_BUFFER_STATE) yy_flex_alloc (sizeof (struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR ("out of dynamic memory in yy_create_buffer()");

  b->yy_buf_size = size;

  /* yy_ch_buf has to be 2 characters longer than the size given because
   * we need to put in 2 end-of-buffer characters.
   */
  b->yy_ch_buf = (char *) yy_flex_alloc (b->yy_buf_size + 2);
  if (!b->yy_ch_buf)
    YY_FATAL_ERROR ("out of dynamic memory in yy_create_buffer()");

  b->yy_is_our_buffer = 1;

  yy_init_buffer (b, file);

  return b;
}


#ifdef YY_USE_PROTOS
void
yy_delete_buffer (YY_BUFFER_STATE b)
#else
void
yy_delete_buffer (b)
     YY_BUFFER_STATE b;
#endif
{
  if (!b)
    return;

  if (b == yy_current_buffer)
    yy_current_buffer = (YY_BUFFER_STATE) 0;

  if (b->yy_is_our_buffer)
    yy_flex_free ((void *) b->yy_ch_buf);

  yy_flex_free ((void *) b);
}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO ((int));
#endif
#endif

#ifdef YY_USE_PROTOS
void
yy_init_buffer (YY_BUFFER_STATE b, FILE * file)
#else
void
yy_init_buffer (b, file)
     YY_BUFFER_STATE b;
     FILE *file;
#endif


{
  yy_flush_buffer (b);

  b->yy_input_file = file;
  b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
  b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
  b->yy_is_interactive = 0;
#else
  b->yy_is_interactive = file ? (isatty (fileno (file)) > 0) : 0;
#endif
#endif
}


#ifdef YY_USE_PROTOS
void
yy_flush_buffer (YY_BUFFER_STATE b)
#else
void
yy_flush_buffer (b)
     YY_BUFFER_STATE b;
#endif

{
  if (!b)
    return;

  b->yy_n_chars = 0;

  /* We always need two end-of-buffer characters.  The first causes
   * a transition to the end-of-buffer state.  The second causes
   * a jam in that state.
   */
  b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
  b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

  b->yy_buf_pos = &b->yy_ch_buf[0];

  b->yy_at_bol = 1;
  b->yy_buffer_status = YY_BUFFER_NEW;

  if (b == yy_current_buffer)
    yy_load_buffer_state ();
}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_buffer (char *base, yy_size_t size)
#else
YY_BUFFER_STATE
yy_scan_buffer (base, size)
     char *base;
     yy_size_t size;
#endif
{
  YY_BUFFER_STATE b;

  if (size < 2 ||
      base[size - 2] != YY_END_OF_BUFFER_CHAR ||
      base[size - 1] != YY_END_OF_BUFFER_CHAR)
    /* They forgot to leave room for the EOB's. */
    return 0;

  b = (YY_BUFFER_STATE) yy_flex_alloc (sizeof (struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR ("out of dynamic memory in yy_scan_buffer()");

  b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
  b->yy_buf_pos = b->yy_ch_buf = base;
  b->yy_is_our_buffer = 0;
  b->yy_input_file = 0;
  b->yy_n_chars = b->yy_buf_size;
  b->yy_is_interactive = 0;
  b->yy_at_bol = 1;
  b->yy_fill_buffer = 0;
  b->yy_buffer_status = YY_BUFFER_NEW;

  yy_switch_to_buffer (b);

  return b;
}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_string (yyconst char *yy_str)
#else
YY_BUFFER_STATE
yy_scan_string (yy_str)
     yyconst char *yy_str;
#endif
{
  int len;
  for (len = 0; yy_str[len]; ++len)
    ;

  return yy_scan_bytes (yy_str, len);
}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_bytes (yyconst char *bytes, int len)
#else
YY_BUFFER_STATE
yy_scan_bytes (bytes, len)
     yyconst char *bytes;
     int len;
#endif
{
  YY_BUFFER_STATE b;
  char *buf;
  yy_size_t n;
  int i;

  /* Get memory for full buffer, including space for trailing EOB's. */
  n = len + 2;
  buf = (char *) yy_flex_alloc (n);
  if (!buf)
    YY_FATAL_ERROR ("out of dynamic memory in yy_scan_bytes()");

  for (i = 0; i < len; ++i)
    buf[i] = bytes[i];

  buf[len] = buf[len + 1] = YY_END_OF_BUFFER_CHAR;

  b = yy_scan_buffer (buf, n);
  if (!b)
    YY_FATAL_ERROR ("bad buffer in yy_scan_bytes()");

  /* It's okay to grow etc. this buffer, and we should throw it
   * away when we're done.
   */
  b->yy_is_our_buffer = 1;

  return b;
}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void
yy_push_state (int new_state)
#else
static void
yy_push_state (new_state)
     int new_state;
#endif
{
  if (yy_start_stack_ptr >= yy_start_stack_depth)
    {
      yy_size_t new_size;

      yy_start_stack_depth += YY_START_STACK_INCR;
      new_size = yy_start_stack_depth * sizeof (int);

      if (!yy_start_stack)
	yy_start_stack = (int *) yy_flex_alloc (new_size);

      else
	yy_start_stack = (int *) yy_flex_realloc (
					 (void *) yy_start_stack, new_size);

      if (!yy_start_stack)
	YY_FATAL_ERROR (
			 "out of memory expanding start-condition stack");
    }

  yy_start_stack[yy_start_stack_ptr++] = YY_START;

  BEGIN (new_state);
}
#endif


#ifndef YY_NO_POP_STATE
static void
yy_pop_state ()
{
  if (--yy_start_stack_ptr < 0)
    YY_FATAL_ERROR ("start-condition stack underflow");

  BEGIN (yy_start_stack[yy_start_stack_ptr]);
}
#endif


#ifndef YY_NO_TOP_STATE
static int
yy_top_state ()
{
  return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void
yy_fatal_error (yyconst char msg[])
#else
static void
yy_fatal_error (msg)
     char msg[];
#endif
{
  (void) fprintf (stderr, "%s\n", msg);
  exit (YY_EXIT_FAILURE);
}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void
yy_flex_strncpy (char *s1, yyconst char *s2, int n)
#else
static void
yy_flex_strncpy (s1, s2, n)
     char *s1;
     yyconst char *s2;
     int n;
#endif
{
  register int i;
  for (i = 0; i < n; ++i)
    s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int
yy_flex_strlen (yyconst char *s)
#else
static int
yy_flex_strlen (s)
     yyconst char *s;
#endif
{
  register int n;
  for (n = 0; s[n]; ++n)
    ;

  return n;
}
#endif


#ifdef YY_USE_PROTOS
static void *
yy_flex_alloc (yy_size_t size)
#else
static void *
yy_flex_alloc (size)
     yy_size_t size;
#endif
{
  return (void *) malloc (size);
}

#ifdef YY_USE_PROTOS
static void *
yy_flex_realloc (void *ptr, yy_size_t size)
#else
static void *
yy_flex_realloc (ptr, size)
     void *ptr;
     yy_size_t size;
#endif
{
  /* The cast to (char *) in the following accommodates both
   * implementations that use char* generic pointers, and those
   * that use void* generic pointers.  It works with the latter
   * because both ANSI C and C++ allow castless assignment from
   * any pointer type to void*, and deal with argument conversions
   * as though doing an assignment.
   */
  return (void *) realloc ((char *) ptr, size);
}

#ifdef YY_USE_PROTOS
static void
yy_flex_free (void *ptr)
#else
static void
yy_flex_free (ptr)
     void *ptr;
#endif
{
  free (ptr);
}

#if YY_MAIN
int
main ()
{
  yylex ();
  return 0;
}
#endif
#line 155 "Compiler/lexin"
