/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#include "../../../../configure.h"
#include "../../../../libAfterStep/asapp.h"
#include "../../../../libAfterStep/module.h"
#include "../../../../libAfterConf/afterconf.h"
#include "../../../../libASGTK/asgtk.h"

#include "interface.h"
#include "support.h"


ASWallpaperState WallpaperState ;

int
main (int argc, char *argv[])
{
	
	init_asgtkapp( argc, argv, CLASS_ASCP, NULL, 0);
	ConnectAfterStep(0,0);
//  add_pixmap_directory (DEFAULT_PIXMAP_DIR);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  init_ASWallpaper();

  gtk_main ();
  return 0;
}

