// generated by Fast Light User Interface Designer (fluid) version 1.0103

#include "ascpui.h"

ASControlPanelUI::ASControlPanelUI() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(363, 279);
    w = o;
    o->user_data((void*)(this));
    { Fl_Tabs* o = new Fl_Tabs(-20, 5, 475, 305);
      o->box(FL_EMBOSSED_BOX);
      o->labeltype(FL_NO_LABEL);
      o->align(FL_ALIGN_TOP_LEFT);
      new Fl_Button(0, 5, 95, 40, "Create new");
      o->end();
    }
    o->end();
    o->show();
  }
}

