// generated by Fast Light User Interface Designer (fluid) version 1.0103

#ifndef ascp_h
#define ascp_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Button.H>

class ASControlPanelUI {
public:
  ASControlPanelUI();
};
#endif
